// <auto-generated />
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221116190524_Global_Tables")]
    partial class Global_Tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Domain.Entity.entradaProduto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("entradaProduto");
                });

            modelBuilder.Entity("Domain.Entity.Produto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Domain.Entity.saidaProduto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("saidaProduto");
                });

            modelBuilder.Entity("Domain.Entity.tabelaCaixa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaCaixa");
                });

            modelBuilder.Entity("Domain.Entity.tabelaContaCapital", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaContaCapital");
                });

            modelBuilder.Entity("Domain.Entity.tabelaContaCorrente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaContaCorrente");
                });

            modelBuilder.Entity("Domain.Entity.tabelaDoador", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaDoador");
                });

            modelBuilder.Entity("Domain.Entity.tabelaEmendaImpositiva", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaEmendaImpositiva");
                });

            modelBuilder.Entity("Domain.Entity.tabelaEmendaParlamentar", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaEmendaParlamentar");
                });

            modelBuilder.Entity("Domain.Entity.tabelaFornecedor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaFornecedor");
                });

            modelBuilder.Entity("Domain.Entity.tabelaQuarto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaQuarto");
                });

            modelBuilder.Entity("Domain.Entity.tabelaResidente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaResidente");
                });

            modelBuilder.Entity("Domain.Entity.tabelaVerbaEstadual", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaVerbaEstadual");
                });

            modelBuilder.Entity("Domain.Entity.tabelaVerbaMucinipal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDeficiencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnyDoenca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmprestimoNome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Entrada")
                        .HasColumnType("REAL");

                    b.Property<string>("FormaDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauDependencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAposentado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePessoaInstituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroQuarto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Saida")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaRemedio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Validade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("dataNiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dataRegistro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabelaVerbaMunicipal");
                });
#pragma warning restore 612, 618
        }
    }
}
